### ISSUE TITLE
I can't get the program to work.

### ISSUE THREAD

**Issue by roswitina** [archiveium/archiveium#99]
The way you describe it, I can't get your program to run and test it. Too bad. 

It would be easier for users with my understanding if you simply provide the required configuration files (all required). That would be enough for a test and in real operation you could swap the required entries beforehand.

Thank you.

**Comment by ParitoshBh** [comment]
I have to admit neither the getting started process nor instructions are the best and definitely needs work. However, is there something in particular that didn't work for you? Were you able to login?

**Comment by roswitina** [comment]
I have to say in advance that I am not really familiar with the configuration files in Docker and the variables. And that is obviously my problem.

I have tried to enter the required variables (data), but I can't get it together. See attached files.

Therefore, my suggestion was that you enclose already working configuration files that also work for a first test and thus also ensure that your PROGRAM is tested with the parameters you intended. This would also have the advantage, not only for users, that they can always assume the same conditions in case of questions or possible bugs.


**config.json**
````
{
        "app": {
                "name": "Archiveium",
                "url": "192.168.1.116",
                "logLevel": "info",
                "useAsCronProcessor": false,
                "adminEmail": "no@name.cc",
                "adminPassword": "archiveiumpw",
                "encryptionKey": "4d6f6e7465766964656f204973204772"
        },
        "database": {
                "user": "archiveium",
                "password": "archiveiumpw",
                "host": "192.168.1.116",
                "port": 5432,
                "database": "archiveiumdb",
                "max": 10
        },
        "redis": {
                "host": "redis",
                "port": 6379
        },
        "search": {
                "host": "meilisearch",
                "port": 7700,
                "apiKey": "4d6f6e7465766964656f204973204772"
        },
        "s3": {
                "endpoint": "http://s3:9000",
                "region": "us-east-1",
                "credentials": {
                        "accessKeyId": "archiveium",
                        "secretAccessKey": "archiveiiumpw"
                },
                "forcePathStyle": true
        },
        "session": {
                "secrets": [""]
        },
        "mail": {
                "host": "",
                "port": 587,
                "secure": false,
                "auth": {
                        "user": "",
                        "pass": ""
                },
                "fromAddress": ""
        }
}
````

**docker-compose.yml**
````
version: '3.8'

services:
  app:
    image: archiveium/archiveium:0.0.29
    restart: always
    ports:
      - 5292:3000
    volumes:
      - ./config.json:/app/config/production-0.json
    environment:
      TZ: 'America/Toronto'           # Change timezone as needed
      NODE_APP_INSTANCE: 0            # Do not change this
      APP_ADMIN_EMAIL: no@name.cc        # Admin Email address
      APP_ADMIN_PASSWORD: archiveiumpw  # Admin Password
      APP_ENCRYPTION_KEY: 4d6f6e7465766964656f204973204772       # Key used for encrypting email account passwords
                                      # changing this key will invalidate all added accounts
                                      # and they'll have to reauthorized again
      SEARCH_API_KEY: '$MEILI_MASTER_KEY'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - archiveium
      # Enable if running behind Traefik
      # - traefik
    depends_on:
      - db
      - redis
      - minio
      - meilisearch
    # Enable if running behind Traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.archiveium.rule=Host(`URL_HERE`)"
    #   - "traefik.http.routers.archiveium.entrypoints=websecure"
    #   - "traefik.http.routers.archiveium.tls.certresolver=cloudflare"
    #   - "traefik.http.services.archiveium.loadbalancer.server.port=3000"

  cron:
    image: archiveium/archiveium:0.0.29
    restart: always
    volumes:
      - ./config.json:/app/config/production-0.json
    environment:
      TZ: 'America/Toronto'       # Change timezone as needed
      NODE_APP_INSTANCE: 0
      USE_AS_CRON_PROCESSOR: true # Needed to run container as cron job processor
      APP_ENCRYPTION_KEY: 4d6f6e7465766964656f204973204772    # Key used for encrypting email account passwords
                                  # changing this key will invalidate all added accounts
                                  # and they'll have to reauthorized again
      SEARCH_API_KEY: '$MEILI_MASTER_KEY'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - archiveium
    depends_on:
      - app
      - db
      - minio
      - meilisearch

  db:
    image: postgres:13
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      PGPASSWORD: "$DB_PASSWORD"          # Should be the same as that of app
      POSTGRES_DB: "$DB_DATABASE"         # Should be the same as that of app
      POSTGRES_USER: "$DB_USERNAME"       # Should be the same as that of app
      POSTGRES_PASSWORD: "$DB_PASSWORD"   # Should be the same as that of app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - archiveium
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

  minio:
    image: 'minio/minio:RELEASE.2023-12-23T07-19-11Z'
    restart: always
    # ports:
    #   - 9000:9000
    environment:
      MINIO_ROOT_USER: '$MINIO_USER'            # Should be the same as that of app
      MINIO_ROOT_PASSWORD: '$MINIO_PASSWORD'    # Should be the same as that of app
      MINIO_COMPRESSION_ENABLE: 'on'
      MINIO_COMPRESSION_EXTENSIONS: ''
      MINIO_COMPRESSION_MIME_TYPES: ''
    volumes:
      - minio_data:/data/minio
    networks:
      - archiveium
    entrypoint: sh
    command: -c 'mkdir -p /data/minio/emails && minio server /data/minio'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:7.4.2-alpine'
    restart: always
    mem_limit: 256M
#    ports:
#      - '6379:6379'
    command: redis-server --maxmemory-policy noeviction --appendonly yes --maxmemory 200M
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      retries: 3
    networks:
      - archiveium

  meilisearch:
    image: getmeili/meilisearch:v1.13.0
    environment:
      - MEILI_MASTER_KEY='$MEILI_MASTER_KEY'
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=true
    ports:
      - 7700:7700
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - archiveium

volumes:
  db_data:
  minio_data:
  redis_data:
  meilisearch_data:

networks:
  archiveium:
  # Enable if running behind Traefik
  # traefik:
  #   external: true
````

````
docker compose pull
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_USERNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_USERNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MINIO_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MINIO_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MEILI_MASTER_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MEILI_MASTER_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MEILI_MASTER_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] /opt/archiveium/docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Pulling 1/55
````
